### ISSUE TITLE
Crackling sound in OSX 10.10 Yosemite

### ISSUE THREAD

**Issue by Janhouse** [RogueAmoeba/Soundflower#19]
Up until I updated to OSX 10.10 audio was good. Now I get crackling/distorted sound when using Soundflower.
Any ideas? I am using latest stable version provided on Google code. (seems to be outdated)
Does anyone else get the same problem with latest GIT version?

If it helps: I'm using Macbook Pro Retina (2013)

**Comment by nickrivadeneira** [comment]
@gcoop I got the same problem as you - Sound Siphon was working, but keyboard volume control didn't work. Using the slider in sound preferences did work. Did you find a fix or did you just go with Boom?

**Comment by gcoop** [comment]
Just went with Boom :)

**Comment by jakemauer** [comment]
@mikemaccana For future reference Audio Midi setup deals with all audio hardware on the computer, not just MIDI devices. It's where you setup audio sample rates, change volumes on specific devices, or create aggregate devices. 

@gcoop I got excited at the SoundSiphon solution however the lack of volume control makes it kind of a bummer to use.

@nickrivadeneira @gcoop Here's my current solution with utilizes aggregate devices and AuLab:

1. Install Soundflower from here: https://github.com/mattingalls/Soundflower/releases (I'm using Version 2.02b)
2. In Audio Midi Setup create an aggregate device that combines the Built-in Output and Soundflower (2-ch) 
3. Set the clock source to Built-In Output
4. Your channel setup will look like this if you clicked 'Built-in Output' first, if not you can drag the output channels into this order: ![Audio Midi Setup](http://cl.ly/image/0H0e1v362S35/Screen%20Shot%202015-01-09%20at%207.17.58%20PM.png)
5. In AuLab create a new document with the audio input device set to Soundflower (2ch) 
6. Set the audio output device to your aggregate device. (Mine was named by default to 'Aggregate Device')
7. Verify Link Channel Groups is checked.
8. Verify the output is set to the same channels as Built-in output in the aggregate device, in my setup it's on channels 1-2. You can drag the outputs around by the brown bar if you need to change the channels. ![AULab Setup](http://cl.ly/image/3I0Z3A2t1N1c/Screen%20Shot%202015-01-09%20at%207.21.41%20PM.png)
9. Next set your system audio output to Soundflower (2ch) and you should be good to go. 

This is a cleaned up version of techniques I gleaned from this conversation: https://www.reddit.com/r/audioengineering/comments/2jpbqm/effects_on_mac_system_sound_without_au_lab/

This isn't a perfect solution, if I play straight sine waves I can hear clicking, however in music, even passages that resulted in clicking when using Soundflower straight, I don't hear any problems. It's good enough for now.

**Comment by CodyGentry** [comment]
I used that exact thread to piece together the same solution, but with Sound Siphon.  It worked for me as well at first, but the clicking seemed to come and go enough that I am still searching for a solution.  Regarding Boom, I can't find out for sure whether it supports AU or VST plugins...

**Comment by rca** [comment]
@jakemauer thanks for the step-by-step.  I tried it and I was only able to get it to work by creating an aggregated device only containing the built-in output.  Once I had everything wired up, go back and add Soundflower to the aggregate.

Unfortunately the crackling was replaced by straight up drops in audio.

I'm going with Boom2.

**Comment by Penbo** [comment]
It is not Soundflower or Sound Siphon, it’s AU Lab.
I can run Wimp HiFi > Soundflower > Amarra Sq > output without ‘clicks’, but when I add Au Lab into the chain, I get clicks (3-5/sek.) again.
Very regrettable, as I had fine tuned an EQ plugin and the sound was great, if not for the clicking noise.

This is in Yosemite OSX 10.10.1 on MacBook Pro 2011

**Comment by CodyGentry** [comment]
Concur; it's got to be AU Lab.  No issues in other applications here, either.  Now I wish I had stuck with the (free) Soundflower over buying Sound Siphon when I thought it was working--nothing against the developer over there. :)

**Comment by Penbo** [comment]
AudioHijack Pro (32bit - payed) or Hosting AU (64bit - free) can substitute AU LAb without noise or cracks.....
AudioHijack Pro without Soundflower and Hosting AU with....

**Comment by CodyGentry** [comment]
That's the one application I have not tried.  I'll look into it.

**Comment by estebanbouza** [comment]
Hosting AU working like charm for me now. No crackling with soundflower. The only difference I find with AU Lab is that when changing system volume, there's a slight delay of about half a second until it's changed. Thanks @Penbo

**Comment by Janhouse** [comment]
Thank you! Hosting AU works like a charm. :+1:

**Comment by Stubetcha** [comment]
Hosting AU seems like a good solution for now. If anyone is having trouble, here is how to use it: http://recordit.co/p3Tas2CHg2

**Comment by troymcginnis** [comment]
Hey guys, I went ahead and installed Hosting AU but can't seem to get Master to output to Built-in Output. It's defaulting to BoomDevice and the Ext-in/Track D input selection only shows BoomDevice, Built-in Microphone, and Soundflower.

Any ideas?

![screenshot 2015-02-03 11 19 16](https://cloud.githubusercontent.com/assets/4299551/6027387/871ffac2-ab96-11e4-8ff5-7e050743adfa.png)

**Comment by yoojin** [comment]
It looks like you aren’t a contributing coder, but are instead attempting to effect some kind of recording on your computer.  I might recommend JACK for OS X, which beside Soundflower attempts to do the same thing.  I hope nobody thinks of this as a personal attack against Soundflower.  I can get JACK to work currently but have a problem with clicking with Soundflower at the moment, and have been using JACK in the mean time.  Were I better skilled at programming I would gladly contribute to the project, and I think it’s delightful that Soundflower’s source is available on GitHub, and the open source is the primary reason I would use Soundflower over the currently working JACK and JACKserver.

Good luck,

Aaron Palmer

**Comment by rolandek** [comment]
I downloaded Soundflower 2.02b from jakemauers link, still the same problem, 
but then I turned off "sound drift correction" and it works fine now, no crackling! 
OSX Yosemite 10.10.2 . Tryed this with Au Lab 2.3.1, AU Hosting 1.3.4, Ableton Live 9, Kontakt 5 & Reaktor 5, all streaming to Reason 8. 

So not sure if 2.02b fixed it, or it just might be enough to turn off sound drift correction on 1.6.6.

Hope it helps someone!

**Comment by oytuneyucel** [comment]
holy moly I was wondering why I never saw this solution when trying to set my Yosemite up with the EQ.. thank you everyone who made the solution possible, I was going nuts with the crackling sound and never thought AU Lab was to blame! glad we do have an alternate with a nice interface.. despite being used by so many audio technicians, and being the one that brought iPods to the stage, it's rather confounding that OSX has such poor audio capabilities :-1:

**Comment by adamcollingburn** [comment]
Hey @rolandek @oytuneyucel - Where abouts do I find the setting for sound drift correction?

**Comment by gunderson** [comment]
I don't have AU Lab and still get choppy sound over displayport audio with soundflower. If I switch to "built-in" then immediately back to "display" the choppiness goes away for an undetermined amount of time then returns.  Affects all sound.

**Comment by rolandek** [comment]
@adamcollingburn Sorry for late reply. In the Audio Midi Setup (in Applications > Utilities)

**Comment by thedamon** [comment]
@gunderson I'm having the same issue, I think. I wasn't sure it was necessarily soundflower, but this thread makes me think it probably is. It happens sporadically but generally in groups. Is it like distorted/garbled for short amounts of time? (sounds like a badly encoded file with audio artifacts..)

**Comment by aski71** [comment]
I'm also getting crackling sounds when routing audio via Soundflower to Logic and then out through my Fireface. :-(

**Comment by ruicout0** [comment]
Still have the same problem. Tried Hosting AU, but still doesn't seem to work...
Is there any proven solution to the crackling sound? Thanks

**Comment by charlienorwood** [comment]
I'm on a late 2013 MBP with OS X 10.10.3 running audio via usb dac to an Oppo HA-2. No matter what I tried with Soundflower+AU Lab I always got clicks. But currently I'm running sound siphon (free version) + AU Hosting and I have zero clicks! Parametric EQ'ing like a champ right now. I have SS, the Oppo and Built in Audio all set to 48khz in Audio Midi Set Up.

![screen shot 2015-06-07 at 9 13 49 am](https://cloud.githubusercontent.com/assets/12784638/8024090/8ee27c2e-0cf5-11e5-8d3b-880625e37e10.png)

**Comment by adamcollingburn** [comment]
Thanks @Stubetcha @charlienorwood - finally came back to this post and installed Hosting AU, works like a charm

**Comment by achterluikje** [comment]
Hosting AU with sound flower or sound siphon worked perfectly for me as well! Tried AU Lab before but this gave crackling sound issues. So issue on Yosemite seems caused by combos with AU Lab from what I've seen. I use it with a presonus itwo btw.

**Comment by HieronymusChris** [comment]
I've been struggling with this for a month now. I was using Soundflower and AU Lab with Yosemite, and finally ditched them both for Sound Siphon and Hosting AU, per the above consensus. Generally sound works much better, as I no longer get crackling after ~20 minutes of use.

However, I slowly get a delay (this was happening with SF/AULab, too) after running audio. It generally tops out at about .5 seconds of delay after ~15 minutes of use. It used to reset itself if I quit/reopened AU Lab. Now with Hosting AU, I found that if I go into my MIDI options and change my output from 44khz to 48khz, then back again, it resets the delay for a short time.

Is there a more permanent solution for this? Changing my buffer size in Hosting AU doesn't seem to help at all. Would love some advice here—my wife is going to kill me because I keep messing up her Netflix watching!

**Comment by daterrell** [comment]
2¢ guys.  I had 1.6.6b installed on 10.10.4, MBP 15" Mid 2014 using headphones directly connected to the laptop.  Serious crackling!  Switching to 1.6.7 fixed it for me.  I even had music playing during the update.  As soon as the new output device showed up I was able to switch over to pristine sound.

Thanks guys!

**Comment by aski71** [comment]
Folks,
I'm still on the rogue amoeba 1.1.6b and was struggling with audio crackling sounds.
Maybe this helps some of you:

My setup is:
Max/MSP using MIDI as input routing the audio output via Soundflower to MainStage and from there to my Fireface UFX.

After experimenting a while I found this in the audio settings (see image):

![audio-settings](https://cloud.githubusercontent.com/assets/5214169/9645379/7a8c750c-51cb-11e5-9ae5-b3d0590de8fb.jpg)

Notice that "Soundflower (64ch)" and the Fireface are checked as in "Use". 
Notice also the check box called "Drift correction".
Depending on what I chose as "Clock source" the drift correction was automatically turned on for the other used device.
So in this case "Clock source" is the Soundflower. Drift correction is checked for the Fireface.
When I now changed the "Clock Source" to "Fireface", drift correction automatically gets checked for "Soundflower" and unchecked for "Fireface".

All this resulted in awful crackling sounds in my configuration.

But:
When I manually uncheck "Drift Correction" the crackling is gone!

And it seems, I'm getting the best results by setting the "Clock Source" to "Soundflower".
Using the Fireface clock still results in an audio crack every once in a while.  

Hope this helps.

**Comment by dikafe** [comment]
Hello all! I would also like to input my observations and the outcome of what has been a long time of looking up information and testing all sort of combinations, in order to get a satisfactory result for my needs (which fortunately seems to have happened(!)). Quite many people in these forums have spent similarly much or more time with such issues, so I hope my findings will contribute in helping others to save some.
**The Problem:** The equipment I wanted to combine is a **Motu Microbook II external sound interface**, **2 monitors** and an **LG DVD receiver** (preferably connected via it's digital input), under **Yosemite 10.10.5 OS**. I mention the brands in case it matters. My intention has been to add the DVD receiver for its subwoofer speaker, which would boost the low frequencies. Most of the solutions I tried though had minor or bigger flows, except one.
**The Solution:** What seems to work so far the best is the use of **Soundflower 2.0b2**, **SoundflowerBed 2.0.0** **AULab 2.3.1**,  the above equipment and the **Built-in Output**. There's no crackling, the output to the DVD receiver is filtered, the two output sources are well synchronized and I'm very pleased so far. For anyone interested in this setup (4th paragraph), please read on for the details.

I thought that I should also mention the failed attempts for the sake of completeness: 
1. My original approach has been the most straight forward one, which regards plugging the input of the DVD receiver to the digital output (which mirrors the main output where the monitors are connected) of the sound card. The drawback, however, was asynchronous audio output between the monitors and the DVD receiver's speakers. The audio was at first synchronized, but later on was slowly starting to lag out of the DVD receiver more and more; sometimes even abruptly. I tried to connect the DVD receiver via it's analog input to sound card's analog output to no avail. The only workaround able to help a bit was either resetting the sound card (in MIDI setup) or the DVD receiver input channel (by switching to another channel and then back to the right one). The audio displace was soon so obvious, however, that this couldn't be a lasting solution. Because of the fact that the playback was synchronous at first and later it was deviating I assumed that is a hardware problem most probably related to the DVD receiver. No matter how much I searched to that direction, I couldn't spot any useful tips.
2. I then tried to connect the DVD receiver directly on the Builtin Output (via again the digital input) and create a Multi Output device in the MIDI setup menu to parallelize the sound card with the DVD receiver. Despite trying all of the output format, bit depth, clock source arrangements and drift correction en/dis-abling, there was no true fix. To the beneficial side, there was some slight improvement in how quickly the deviation between the two audio outputs was becoming noticeable in comparison to the previous method and I could now reset the synchronization by just reselecting the bit depth of the Builtin Output, action that would pause only the sound coming from the DVD receiver speakers (the monitors were still playing). In general these results reinforced my assumption that is a hardware issue (to this date, I'm still not sure if it is actually related).
3. Since the deviation was more obvious at the mid and high frequencies and I was interested in only the lower ones for the DVD receiver (remember?), I thought to filter the Builtin output if possible. It was then that I started to mess with Soundflower, AULab and the similar software. I am explaining the precise setup in the final solution, but in short:
- Case 1: AuLab (with a LowPass Filter) settings: input device: Soundflower(2ch), output device: Builtin Output, result -> Surprised to get much better synchronized audio (why?) that would need resetting less frequently. The big disadvantage: quite annoying crackling sounds from the Builtin output, as been described by many users.
- Case 2: AuLab with Soundsiphon : No crackling but again asynchronous output since the very first moment actually. I uninstalled Soundsiphon.
- Case 3: AuLab with Boom2: The quality of sound seemed ok, but I could not control the volume level from the keyboard. Also no options in Boom for exact settings (beautiful but oversimplified menu). I'm also not sure if it's related, if I missed something or what, but after uninstalling Boom, I couldn't get audio with the same setup I was using before (using Soundflower). Anyway, I uninstalled everything and installed back and it worked.

4 . **Final Pleasing Solution**: With this solution there is no crackling distortion, I'm using only freeware and the audio output is well synchronized among the two output sources (I expect some mismatch would happen every now and then, but I haven't used it for an extended time to tell how often yet).
- Audio MIDI Setup settings as shown in the picture:

![audiomidisetup settings](https://cloud.githubusercontent.com/assets/15359341/10789816/53ca3da8-7d88-11e5-890a-7fd34bd8c728.png)

Notice that the Multi-Output Soundflower device has only the Soundflower(2ch) output assigned
Not Sure if the drift correction options are necessary.
- AULab settings:

![aulab settings](https://cloud.githubusercontent.com/assets/15359341/10789678/80bafd80-7d87-11e5-824c-e7b6764c460d.png)
- SoundflowerBed settings:

![soundflowerbed settings](https://cloud.githubusercontent.com/assets/15359341/10789519/8ba4df50-7d86-11e5-8323-cfcfcf53ca3d.png)

In order to have (raw) audio through the sound card as well, I have checked the Multi-Output Device, while normally I would have selected "None" for a single output case. With the current configuration I was able to get unfiltered audio towards the sound card's input and filtered via AULab to the DVD receiver's input. I am explaining below why I have created a Multi-Output device with only the Motu sound card assigned, to which Soundflower sends the audio, instead of sending it directly to the sound card. 

I know it's a rather complicated and awkward setup, product of a trial and error process and I don't really understand why it works better than the other methods, but at least it does!

Side notes:
- I would be very interested to know why the 1st or 2nd (rather straightforward) solutions tend to desynchronize the outputs and if it's possible to measure the delta or fix it. Moreover, the DVD receiver's menu lacks of any precise setting, like delay adjustment or similar.
- The reason I'm using the Multi-Output device for the sound card is the following. Soundflower sends audio to all of the selected device's (here the sound card) channels (regardless if the "Clone to all channels" is checked or not). Therefore due to this fact and when using Mixxx (djing software), where I need independent (stereo) channels for Master and Headphones output,  there is always sound coming out of the Headphones either I have muted their channel or not. Also the soundcard's settings are bypassed by Soundflower for some reason. By creating this Multi-Output device however and parenting it to the soundcard, this drawback is resolved. Now the sound card settings are applied and I only have to mute the Headphones channel there to avoid receiving audio from Soundflower...

That's all folks and I apologize for my english! :)

**Comment by HieronymusChris** [comment]
Holy guacamole! I can’t wait to get home and try this out.

Thank you for the fantastic writeup! Glad you have something that’s working. Will update as soon as I’m able to try it out.

**Comment by dikafe** [comment]
Hehe! Thank you, but you'd need another day to first read through and understand my text, I guess! :laughing: 
But seriously, just ask me anything if you need me to focalize to a certain point or even clarify further(!)...

**Comment by dikafe** [comment]
**EDIT:** I should mention that with the configuration I've described above, the sound crackles sometimes, if I start messing with the settings. It has happened though that at some point it gets fixed. **HOWEVER** I found [this post](https://www.reddit.com/r/audioengineering/comments/2jpbqm/effects_on_mac_system_sound_without_au_lab/), where user **czdl** describes a simpler and better explained setup, which proves to perform pretty sharply so far! I believe people with crackling/popping effects in Yosemite should follow this user's instructions...

Btw, with the previous configuration I could not also save the document with the settings in AULab. By selecting the Aggregate device in both of the input and output settings -as instructed by czdl-, it is now possible to normally save the file.

**Comment by jorgecolonconsulting** [comment]
I tried Hosted AU with SoundFlower on Yosemite and so far the seems to have fixed the crackling.

**Comment by onnlinetool** [comment]
Downloaden Knack  Downloaden Knack  Downloaden Knack

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

**Comment by tanyanghan** [comment]
rolandek solved the crackling sound problem for me in his post [above](https://github.com/RogueAmoeba/Soundflower-Original/issues/19#issuecomment-72836896). Just turn off Drift Correction in the Audio MIDI Setup. This is on standalone Soundflower 2.0b2.

Someone mentioned about echo/reverb in the recording, that is caused by the "volume" slider in the QuickTime Screen Recording. The slider doesn't appear to be volume control but adds some sort of reverb effect, so just leave the slider to the left most (off) and no more echo/reverb.

**Comment by alsc-tr** [comment]
Just started using AU Lab (2.3) and Soundflower (2.0b2) and I also get crackling noise after around 20-30 mins which gets worse over time. I don't have a Drift Correction box in the MIDI Setup. Any solutions?

**Comment by mattingalls** [comment]
@AlexanderSchmedes - Assuming you are doing something like Soundflower for input, and Built-in for output, yeah, i wouldn't be surprised if AU Lab doesn't do any drift correction internally.  You could try creating an aggregate device with the 2 devices and turn on drift correction next to Soundflower.  Then use the aggregate device in AULab for both the output and input device.

**Comment by anandmadras** [comment]
Culprit is AU LAB Not the Soundflower. Use Hosting AU instead

**Comment by vrnvorona** [comment]
Increasing buffer size helped me.
