### ISSUE TITLE
How to feed audio from Hijack through Sunflower to Dictation on a Mac

### ISSUE THREAD

**Issue by utdpauls** [RogueAmoeba/Soundflower#32]
I'm running a fairly new Macbook Pro with Yosemite 10.10.3.

I have purchased RogueAmoeba's Audio Hijack and successfully recorded an mp3 from a ustream of a conference.  How I want to create a transcript.  I found instructions on the web http://telestreamblog.telestream.net/2013/12/using-dictation-to-turn-recorded-audio-to-text-2/ and followed them, but it's not working.

I have the output device in Audio Hijack set to Sunflower2ch and the input to Dictation set to Sunflower2ch, but, when I launch iTunes to play the mp3, I don't get any dictation in TextEdit.

Audio Hijacks animation shows that the audio is running.  Dictation's animation shows that it's receiving the audio feed.  But, as soon as I launch TextEdit and start dictation, the animation in Dictation stops.  If I kill dictation in TextEdit, Dictation's animation starts moving again, indicating that it's receiving audio from Audio Hijack.  Substituting Microsoft Word results in the exact same behavior.  So does running it in Pages.

I have used both iTunes and Quicktime Player as the input device.  Both work exactly the same.  As soon as I start dictation in the recording app (TextEdit, Pages or Word), the animation in Dictation goes dead, and no text is written to the file.

If I switch to the internal microphone, dictation works as expected.

What might I be doing wrong?

**Comment by qdcarnicelli** [comment]
utdpauls  - If you haven't already, send this all into https://rogueamoeba.com/support/supportRequest.php and we can get you sorted out.

Thanks.

**Comment by utdpauls** [comment]
I already did, and they sent me here.

**Comment by illusionofchaos** [comment]
The answer from [here](http://apple.stackexchange.com/a/188367): 

The problem is not the SoundFlower. In Yosemite, Whenever we try to use the dictation feature in OSX it mutes other sounds and active only the build-in microfone. You need to set some hidden preferences to make this work. Open Terminal and enter the two commands below:

```
defaults write com.apple.SpeechRecognitionCore AllowAudioDucking -bool NO
defaults write com.apple.speech.recognition.AppleSpeechRecognition.prefs DictationIMAllowAudioDucking -bool NO
```

After doing this turn off dictation in Systems Preferences, wait a few seconds and then re-enable it. You should now be able to dictate while audio is playing. I’ve only tried this while using a headset/headphones, it’s probably not advisable without. :)

To restore your system to it’s virginal state, run these commands in Terminal and then restart dictation:

```
defaults delete com.apple.SpeechRecognitionCore AllowAudioDucking
defaults delete com.apple.speech.recognition.AppleSpeechRecognition.prefs DictationIMAllowAudioDucking
```
